In [ ]:
import random 
import pandas as pd
import seaborn as sns

In [ ]:
delivery = pd.read_csv('https://gist.githubusercontent.com/altinodantas/2d57753e48eeacd20a6c1ff6ebe94f6d/raw/e6868648a75a340a651b5494e0f210f1010810aa/dados-delivery.csv')

In [ ]:
delivery

,Produto,dia-da-semana,hora-do-pedido,tempo-entrega,tempo-entrega-real,data-pedido,valor,atraso,avaliacao
0,A,4.0,14.0,15.0,15.0,12/24/2020,39.0,0.0,10.0
1,A,7.0,13.0,15.0,60.0,12/16/2020,10.0,1.0,0.0
2,B,7.0,14.0,30.0,30.0,12/27/2020,30.0,0.0,9.0
3,A,3.0,13.0,45.0,15.0,12/17/2020,44.0,0.0,8.0
4,B,6.0,13.0,60.0,75.0,12/18/2020,23.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...
527,F,1.0,5.0,35.0,60.0,12/8/2020,22.0,1.0,3.0
528,H,6.0,14.0,90.0,110.0,12/23/2020,72.0,1.0,0.0
529,E,6.0,1.0,95.0,125.0,12/10/2020,60.0,1.0,0.0
530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Amostra estratificada de tamanho 150

In [ ]:
amostra_simples = delivery.sample(n=150)
amostra_simples

,Produto,dia-da-semana,hora-do-pedido,tempo-entrega,tempo-entrega-real,data-pedido,valor,atraso,avaliacao
47,G,3.0,14.0,115.0,65.0,12/29/2020,39.0,0.0,10.0
295,B,4.0,18.0,140.0,15.0,12/20/2020,20.0,0.0,9.0
111,E,5.0,14.0,85.0,110.0,12/2/2020,28.0,1.0,4.0
407,A,7.0,6.0,70.0,125.0,12/29/2020,7.0,1.0,2.0
525,G,5.0,21.0,50.0,130.0,12/23/2020,25.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
134,B,1.0,13.0,85.0,55.0,12/24/2020,48.0,0.0,10.0
126,G,5.0,13.0,10.0,20.0,12/21/2020,12.0,1.0,3.0
315,G,4.0,21.0,65.0,105.0,12/9/2020,19.0,1.0,2.0
62,G,7.0,14.0,140.0,125.0,12/8/2020,29.0,0.0,9.0
52,C,6.0,12.0,50.0,15.0,12/6/2020,26.0,0.0,10.0

In [ ]:
amostra_simples.groupby('Produto ')[['valor']].count()

          valor
Produto
65            0
A            17
B            19
C            12
D            17
E            16
F            15
G            18
H            16
I            16
V             1
X             1

### Amostra estratificada proporcional de 20%

In [ ]:
amostra_estratificada_d = delivery.groupby('Produto ', group_keys=False).apply(lambda grupo: grupo.sample(frac=.2))

amostra_estratificada_d

,Produto,dia-da-semana,hora-do-pedido,tempo-entrega,tempo-entrega-real,data-pedido,valor,atraso,avaliacao
317,A,2.0,21.0,25.0,140.0,12/22/2020,12.0,1.0,1.0
248,A,4.0,19.0,110.0,175.0,12/24/2020,14.0,1.0,0.0
426,A,3.0,1.0,115.0,175.0,12/29/2020,2.0,1.0,4.0
523,A,1.0,9.0,70.0,35.0,12/24/2020,20.0,0.0,9.0
325,A,4.0,20.0,175.0,160.0,12/31/2020,8.0,0.0,9.0
...,...,...,...,...,...,...,...,...,...
166,I,5.0,13.0,135.0,100.0,12/3/2020,22.0,0.0,8.0
152,I,5.0,12.0,180.0,60.0,12/18/2020,35.0,0.0,10.0
194,I,5.0,13.0,100.0,65.0,12/14/2020,7.0,0.0,9.0
393,I,4.0,21.0,135.0,160.0,12/13/2020,15.0,1.0,6.0
213,I,7.0,21.0,135.0,55.0,12/10/2020,4.0,0.0,10.0